"use client";

import { useRef, useState } from "react";

export function ImportSection({
  jsonText,
  onJsonTextChange,
  error,
  isParsing,
  onAnalyze,
  onUploadFile,
  onPaste,
}: {
  jsonText: string;
  onJsonTextChange: (v: string) => void;
  error: string | null;
  isParsing: boolean;
  onAnalyze: () => void;
  onUploadFile: (file: File) => void;
  onPaste: () => void;
}) {
  const [isDragging, setIsDragging] = useState(false);
  const dragDepthRef = useRef(0);
  const fileInputRef = useRef<HTMLInputElement | null>(null);

  return (
    <section className="space-y-6">
      <div className="space-y-2">
        <h2 className="text-3xl font-bold tracking-tight text-foreground md:text-[32px]">Import Data</h2>
        <p className="max-w-2xl text-lg text-on-surface-variant">
          Upload a Lighthouse JSON report or paste the payload to begin analysis.
        </p>
      </div>

      <div className="grid grid-cols-1 gap-6 lg:grid-cols-3">
        <div className="card-surface p-6 md:p-8 lg:col-span-2">
          <h3 className="mb-6 text-2xl font-semibold text-foreground">Upload JSON Report</h3>

          <button
            type="button"
            className={`drop-zone flex w-full cursor-pointer flex-col items-center justify-center rounded-lg bg-background p-10 text-center ${isDragging ? "drop-zone-active" : ""}`}
            onClick={() => fileInputRef.current?.click()}
            onDragEnter={(e) => {
              e.preventDefault();
              dragDepthRef.current += 1;
              setIsDragging(true);
            }}
            onDragOver={(e) => e.preventDefault()}
            onDragLeave={(e) => {
              e.preventDefault();
              dragDepthRef.current = Math.max(0, dragDepthRef.current - 1);
              if (dragDepthRef.current === 0) setIsDragging(false);
            }}
            onDrop={(e) => {
              e.preventDefault();
              dragDepthRef.current = 0;
              setIsDragging(false);
              const file = e.dataTransfer.files?.[0];
              if (file) onUploadFile(file);
            }}
          >
            <div className="mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-primary-container text-on-primary-container">
              <span className="material-symbols-outlined text-3xl">cloud_upload</span>
            </div>
            <span className="mb-1 text-sm font-semibold text-primary">
              {isDragging ? "Drop JSON to import" : "Click to browse or drag & drop"}
            </span>
            <span className="text-base text-on-surface-variant">Supports .json files generated by Lighthouse</span>
            <input
              ref={fileInputRef}
              type="file"
              accept="application/json,.json"
              className="hidden"
              onChange={(e) => {
                const file = e.target.files?.[0];
                if (file) onUploadFile(file);
                e.target.value = "";
              }}
            />
          </button>

          <div className="my-6 flex items-center gap-4">
            <div className="h-px flex-1 bg-outline-variant" />
            <span className="text-xs font-semibold tracking-wider text-on-surface-variant">OR PASTE JSON</span>
            <div className="h-px flex-1 bg-outline-variant" />
          </div>

          <textarea
            value={jsonText}
            onChange={(e) => onJsonTextChange(e.target.value)}
            onKeyDown={(e) => {
              if ((e.ctrlKey || e.metaKey) && e.key === "Enter") {
                e.preventDefault();
                onAnalyze();
              }
            }}
            placeholder='{ "lighthouseVersion": "...", "categories": { ... } }'
            className="min-h-[140px] w-full resize-y rounded-lg border border-outline-variant bg-background p-4 font-mono text-sm text-foreground outline-none transition focus:border-primary focus:ring-1 focus:ring-primary"
          />

          <div className="mt-6 flex flex-wrap items-center justify-end gap-2">
            <button
              type="button"
              onClick={onPaste}
              disabled={isParsing}
              className="cursor-pointer rounded-lg border border-border bg-surface px-4 py-2.5 text-sm font-semibold text-foreground disabled:opacity-50"
            >
              Paste from clipboard
            </button>
            <button
              type="button"
              onClick={onAnalyze}
              disabled={isParsing}
              className="inline-flex cursor-pointer items-center gap-2 rounded-lg bg-primary px-5 py-2.5 text-sm font-semibold text-on-primary transition hover:bg-surface-tint disabled:opacity-50"
            >
              <span className="material-symbols-outlined text-base">analytics</span>
              {isParsing ? "Parsing…" : "Analyze Data"}
            </button>
          </div>

          <p className="mt-3 text-xs text-on-surface-variant">
            Shortcut: <span className="font-semibold">Ctrl+Enter</span> to analyze.
          </p>

          {error ? (
            <div className="mt-4 rounded-lg border border-error/30 bg-error-container p-3 text-sm text-error">
              {error}
            </div>
          ) : null}
        </div>

        <div className="card-surface p-6">
          <h3 className="mb-4 text-2xl font-semibold text-foreground">How to get a report</h3>
          <ol className="list-decimal space-y-3 pl-5 text-base text-on-surface-variant marker:font-bold marker:text-primary">
            <li>Open Chrome DevTools (F12)</li>
            <li>
              Navigate to the <strong className="text-foreground">Lighthouse</strong> tab
            </li>
            <li>
              Click <strong className="text-foreground">Analyze page load</strong>
            </li>
            <li>
              Open the <span className="material-symbols-outlined text-sm">more_vert</span> menu
            </li>
            <li>
              Select <strong className="text-foreground">Save as JSON</strong>
            </li>
          </ol>
        </div>
      </div>
    </section>
  );
}
